<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('assets', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('alt')->nullable();
            $table->json('caption')->nullable();
            $table->string('visibility', 255)->nullable()->default('public');
            $table->text('upload_path')->nullable();
            $table->string('kind', 255)->nullable()->default('image');
            $table->json('metadata')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('service_categories', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('description')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('services', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('short_description')->nullable();
            $table->json('long_description')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->string('icon', 255)->nullable();
            $table->unsignedBigInteger('image_media_id')->nullable()->index();
            $table->unsignedBigInteger('service_category_id')->nullable()->index();
            $table->string('pricing_type', 255)->nullable()->default('on_request');
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('service_features', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('service_id')->nullable()->index();
            $table->json('text')->nullable();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('service_packages', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('service_id')->nullable()->index();
            $table->json('name')->nullable();
            $table->decimal('price', 12, 2)->default(0);
            $table->string('currency', 255)->nullable()->default('EGP');
            $table->json('features')->nullable();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('project_categories', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('description')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('projects', function (Blueprint $table): void {
            $table->id();
            $table->json('title')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->unsignedBigInteger('project_category_id')->nullable()->index();
            $table->string('client', 255)->nullable();
            $table->json('duration')->nullable();
            $table->json('overview')->nullable();
            $table->json('challenge')->nullable();
            $table->json('solution')->nullable();
            $table->json('result')->nullable();
            $table->string('main_media_type', 255)->nullable()->default('image');
            $table->unsignedBigInteger('main_media_id')->nullable()->index();
            $table->unsignedBigInteger('main_media_poster_id')->nullable()->index();
            $table->unsignedBigInteger('main_media_mobile_id')->nullable()->index();
            $table->string('live_url', 2048)->nullable();
            $table->json('tech_stack')->nullable();
            $table->unsignedBigInteger('testimonial_id')->nullable()->index();
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('project_media', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('project_id')->nullable()->index();
            $table->unsignedBigInteger('media_id')->nullable()->index();
            $table->string('type', 255)->nullable()->default('image');
            $table->json('caption')->nullable();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('project_metrics', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('project_id')->nullable()->index();
            $table->json('label')->nullable();
            $table->string('value', 255)->nullable();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('pages', function (Blueprint $table): void {
            $table->id();
            $table->json('title')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->json('excerpt')->nullable();
            $table->string('hero_type', 255)->nullable()->default('image');
            $table->unsignedBigInteger('hero_media_id')->nullable()->index();
            $table->unsignedBigInteger('hero_poster_id')->nullable()->index();
            $table->json('content')->nullable();
            $table->string('template', 255)->nullable()->default('standard');
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('page_media', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('page_id')->nullable()->index();
            $table->unsignedBigInteger('media_id')->nullable()->index();
            $table->string('kind', 255)->nullable()->default('gallery_image');
            $table->json('caption')->nullable();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('menu_locations', function (Blueprint $table): void {
            $table->id();
            $table->string('key', 255)->nullable()->index();
            $table->json('name')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->unique('key');
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('menu_items', function (Blueprint $table): void {
            $table->id();
            $table->json('title')->nullable();
            $table->unsignedBigInteger('menu_location_id')->nullable()->index();
            $table->unsignedBigInteger('parent_id')->nullable()->index();
            $table->string('type', 255)->nullable()->default('route');
            $table->string('route_name', 255)->nullable();
            $table->string('url', 2048)->nullable();
            $table->unsignedBigInteger('page_id')->nullable()->index();
            $table->string('dynamic_source', 255)->nullable();
            $table->string('dynamic_mode', 255)->nullable()->default('selected');
            $table->json('dynamic_items')->nullable();
            $table->integer('dynamic_category_id')->nullable();
            $table->boolean('dynamic_featured')->default(false)->index();
            $table->integer('dynamic_limit')->nullable()->default(8);
            $table->string('icon', 255)->nullable();
            $table->boolean('target_blank')->default(false)->index();
            $table->string('visibility', 255)->nullable()->default('all');
            $table->boolean('is_active')->default(true)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('sliders', function (Blueprint $table): void {
            $table->id();
            $table->string('name', 255)->nullable();
            $table->string('location', 255)->nullable()->index()->default('home_hero');
            $table->boolean('autoplay')->default(true)->index();
            $table->integer('autoplay_speed')->nullable()->default(6500);
            $table->boolean('draggable')->default(true)->index();
            $table->boolean('arrows')->default(true)->index();
            $table->boolean('dots')->default(true)->index();
            $table->boolean('loop')->default(true)->index();
            $table->boolean('is_active')->default(true)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('slides', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('slider_id')->nullable()->index();
            $table->json('title')->nullable();
            $table->json('description')->nullable();
            $table->string('desktop_media_type', 255)->nullable()->default('image');
            $table->unsignedBigInteger('desktop_media_id')->nullable()->index();
            $table->unsignedBigInteger('desktop_poster_id')->nullable()->index();
            $table->string('mobile_media_type', 255)->nullable()->default('image');
            $table->unsignedBigInteger('mobile_media_id')->nullable()->index();
            $table->unsignedBigInteger('mobile_poster_id')->nullable()->index();
            $table->json('button_text')->nullable();
            $table->string('button_url', 2048)->nullable();
            $table->string('button_color', 255)->nullable()->default('#D3968C');
            $table->string('button_text_color', 255)->nullable()->default('#0A3323');
            $table->string('button_hover_color', 255)->nullable()->default('#F7F4D5');
            $table->string('text_color', 255)->nullable()->default('#F7F4D5');
            $table->integer('overlay_opacity')->nullable()->default(35);
            $table->string('video_advance', 255)->nullable()->default('ended');
            $table->integer('sort_order')->nullable()->default(0);
            $table->boolean('is_active')->default(true)->index();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('post_categories', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('description')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('posts', function (Blueprint $table): void {
            $table->id();
            $table->json('title')->nullable();
            $table->json('slug')->nullable();
            $table->string('status', 255)->nullable()->index()->default('draft');
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->json('excerpt')->nullable();
            $table->json('content')->nullable();
            $table->unsignedBigInteger('featured_media_id')->nullable()->index();
            $table->unsignedBigInteger('post_category_id')->nullable()->index();
            $table->unsignedBigInteger('author_id')->nullable()->index();
            $table->dateTime('published_at')->nullable()->index();
            $table->json('meta_title')->nullable();
            $table->json('meta_description')->nullable();
            $table->json('keywords')->nullable();
            $table->string('canonical', 2048)->nullable();
            $table->unsignedBigInteger('og_image_id')->nullable()->index();
            $table->boolean('seo_index')->default(true)->index();
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('tags', function (Blueprint $table): void {
            $table->id();
            $table->json('name')->nullable();
            $table->json('slug')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->string('slug_ar')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.ar'))")->unique();
            $table->string('slug_en')->virtualAs("JSON_UNQUOTE(JSON_EXTRACT(slug, '$.en'))")->unique();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('testimonials', function (Blueprint $table): void {
            $table->id();
            $table->string('client_name', 255)->nullable();
            $table->json('client_company')->nullable();
            $table->unsignedBigInteger('avatar_media_id')->nullable()->index();
            $table->json('quote')->nullable();
            $table->integer('rating')->nullable()->default(5);
            $table->boolean('is_approved')->default(false)->index();
            $table->boolean('is_featured')->default(false)->index();
            $table->unsignedBigInteger('project_id')->nullable()->index();
            $table->integer('sort_order')->nullable()->default(0);
            $table->boolean('is_active')->default(true)->index();
            $table->boolean('is_demo')->default(false)->index();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('methodology_steps', function (Blueprint $table): void {
            $table->id();
            $table->json('title')->nullable();
            $table->json('description')->nullable();
            $table->json('deliverable')->nullable();
            $table->string('icon', 255)->nullable();
            $table->integer('number')->nullable()->default(1);
            $table->integer('sort_order')->nullable()->default(0);
            $table->boolean('is_active')->default(true)->index();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('leads', function (Blueprint $table): void {
            $table->id();
            $table->string('name', 255)->nullable();
            $table->string('phone', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->unsignedBigInteger('service_id')->nullable()->index();
            $table->text('message')->nullable();
            $table->string('source', 255)->nullable()->index()->default('form');
            $table->string('status', 255)->nullable()->index()->default('new');
            $table->text('internal_notes')->nullable();
            $table->dateTime('follow_up_at')->nullable()->index();
            $table->string('locale', 255)->nullable()->default('ar');
            $table->boolean('is_demo')->default(false)->index();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('translations', function (Blueprint $table): void {
            $table->id();
            $table->string('key', 255)->nullable()->index();
            $table->json('value')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->unique('key');
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('redirects', function (Blueprint $table): void {
            $table->id();
            $table->string('from_path', 255)->nullable()->index();
            $table->string('to_path', 255)->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('export_runs', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('user_id')->nullable()->index();
            $table->string('module', 255)->nullable();
            $table->json('ids')->nullable();
            $table->json('columns')->nullable();
            $table->string('locale', 255)->nullable()->default('ar');
            $table->string('status', 255)->nullable()->index()->default('queued');
            $table->string('file_path', 255)->nullable();
            $table->integer('row_count')->nullable()->default(0);
            $table->text('error')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->index('created_at');
        });
        Schema::create('settings', function (Blueprint $table): void {
            $table->id();
            $table->string('group')->index();
            $table->string('key')->unique();
            $table->json('value')->nullable();
            $table->timestamps();
        });
        Schema::create('project_service', function (Blueprint $table): void {
            $table->foreignId('project_id')->constrained()->cascadeOnDelete();
            $table->foreignId('service_id')->constrained()->cascadeOnDelete();
            $table->primary(['project_id', 'service_id']);
        });
        Schema::create('post_tag', function (Blueprint $table): void {
            $table->foreignId('post_id')->constrained()->cascadeOnDelete();
            $table->foreignId('tag_id')->constrained()->cascadeOnDelete();
            $table->primary(['post_id', 'tag_id']);
        });
        Schema::table('users', function (Blueprint $table): void {
            $table->boolean('is_active')->default(true);
            $table->string('locale')->default('ar');
            $table->string('theme')->default('system');
            $table->unsignedBigInteger('avatar_media_id')->nullable();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('post_tag');
        Schema::dropIfExists('project_service');
        Schema::dropIfExists('settings');
        Schema::dropIfExists('export_runs');
        Schema::dropIfExists('redirects');
        Schema::dropIfExists('translations');
        Schema::dropIfExists('leads');
        Schema::dropIfExists('methodology_steps');
        Schema::dropIfExists('testimonials');
        Schema::dropIfExists('tags');
        Schema::dropIfExists('posts');
        Schema::dropIfExists('post_categories');
        Schema::dropIfExists('slides');
        Schema::dropIfExists('sliders');
        Schema::dropIfExists('menu_items');
        Schema::dropIfExists('menu_locations');
        Schema::dropIfExists('page_media');
        Schema::dropIfExists('pages');
        Schema::dropIfExists('project_metrics');
        Schema::dropIfExists('project_media');
        Schema::dropIfExists('projects');
        Schema::dropIfExists('project_categories');
        Schema::dropIfExists('service_packages');
        Schema::dropIfExists('service_features');
        Schema::dropIfExists('services');
        Schema::dropIfExists('service_categories');
        Schema::dropIfExists('assets');
        Schema::table('users', fn (Blueprint $table) => $table->dropColumn(['is_active', 'locale', 'theme', 'avatar_media_id', 'deleted_at']));
    }
};
